spring:
    # activemq 基本配置
    activemq:
        broker-url: tcp://127.0.0.1:61616
        in-memory: false
        # 启用连接池
        pool:
            enabled: true
            max-connections: 15
    # 该配置控制采用 queue 还是 topic模式 true为队列 fasle 为topic 默认为false
    jms:
        pub-sub-domain: false

    # rabbitmq 基本配置
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: guest
        password: guest
        # 虚拟主机,可以实现用户隔离
        virtual-host: /